-- Tabelas - HC Acesso Fácil

DROP TABLE T_ATENDIMENTO;
DROP TABLE T_CLIENTE;
DROP TABLE T_ESPECIALISTA;

CREATE TABLE T_CLIENTE (
    ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NM_CLIENTE VARCHAR2(80) NOT NULL,
    DS_EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    NR_TELEFONE VARCHAR2(20) NOT NULL
);

CREATE TABLE T_ESPECIALISTA (
    ID_ESPECIALISTA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NM_ESPECIALISTA VARCHAR2(80) NOT NULL,
    DS_ESPECIALIDADE VARCHAR2(60) NOT NULL,
    NR_CRM VARCHAR2(20) NOT NULL
);


CREATE TABLE T_ATENDIMENTO (
    ID_ATENDIMENTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE NUMBER NOT NULL,
    ID_ESPECIALISTA NUMBER NOT NULL,
    DS_ATENDIMENTO VARCHAR2(500) NOT NULL,
    DT_ATENDIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ST_ATENDIMENTO VARCHAR2(30) DEFAULT 'AGENDADO',

    CONSTRAINT FK_ATEND_CLIENTE FOREIGN KEY (ID_CLIENTE)
        REFERENCES T_CLIENTE(ID_CLIENTE)
        ON DELETE CASCADE,

    CONSTRAINT FK_ATEND_ESPECIALISTA FOREIGN KEY (ID_ESPECIALISTA)
        REFERENCES T_ESPECIALISTA(ID_ESPECIALISTA)
        ON DELETE CASCADE
);

CREATE INDEX IDX_ATEND_CLIENTE ON T_ATENDIMENTO(ID_CLIENTE);
CREATE INDEX IDX_ATEND_ESPEC ON T_ATENDIMENTO(ID_ESPECIALISTA);


INSERT INTO T_CLIENTE (NM_CLIENTE, DS_EMAIL, NR_TELEFONE)
VALUES ('Neymar Jr', 'neymar.jr@email.com', '11999998888');

INSERT INTO T_ESPECIALISTA (NM_ESPECIALISTA, DS_ESPECIALIDADE, NR_CRM)
VALUES ('Dra. Cristiano Ronaldo', 'Cardiologista', 'CRM12345SP');

INSERT INTO T_ATENDIMENTO (ID_CLIENTE, ID_ESPECIALISTA, DS_ATENDIMENTO, ST_ATENDIMENTO)
VALUES (1, 1, 'Consulta inicial de avaliação', 'CONCLUÍDO');

COMMIT;
